CREATE TABLE Orders (
    orderID BIGINT PRIMARY KEY AUTO_INCREMENT,
    ChosenMovie VARCHAR(255) NOT NULL,
    Amount INT NOT NULL,
    FirstName VARCHAR(255) NOT NULL,
    LastName VARCHAR(255) NOT NULL,
    PhoneNr VARCHAR(255) NOT NULL,
    Email VARCHAR(255) NOT NULL
);